### ISSUE TITLE
Corregir errores

### ISSUE THREAD

**Issue by Miguel056** [Ricardo55010/Proyecto-Estructura-de-datos#2]
@Ricardo55010  marca errores en la función agregarRegistroCola y actualizarRegistroCola

**Comment by Ricardo55010** [comment]
@Miguel056  muchas gracias por la observación compañero , ya están corregidos los errores de sintáxis en las funciones agregarRegistroCola y actualizarRegistroCola , con esto ya podemos generar de forma satisfactoria el archivo cita.o
