### ISSUE TITLE
Violacion de segmento

### ISSUE THREAD

**Issue by Ricardo55010** [Ricardo55010/Proyecto-Estructura-de-datos#4]
Buenas noches  prof @norman-ipn , tenemos una duda con la codificación del proyecto. En nuestro proyecto estamos usando datos de tipo char*[20] para agendar los nombres de las personas,los pedimos con un scanf de la siguiente manera scanf("%s",&nombre), pero manda warning por no ser el tipo de dato apropiado para el formato %s, la solución que encontramos es colocar el scanf sin el '&' scanf("%s",nombre) , esto quita el warning, pero genera una violación de segmento al llamar a la función agregar, ¿es correcto el uso que queremos darle?

**Comment by Ricardo55010** [comment]
La violación segmento al llamar la función agregarRegistroCola en main.c genera el siguiente mensaje :
> make: *** [Makefile:8: run] Violación de segmento (core dumped) [Núcleo vaciado a un archivo]

En cambio cuando colocamos el & dentro de scanf se genera el siguiente warning:

> > 
> el formato '%s' espera tipo 'char', pero el argumento 2 es de tipo char*[20]

**Comment by Miguel056** [comment]
Buenas noches, yo también tengo el mismo warning al poner el "&" en el scanf, investigando vimos que era sin el "&" pero nos genera otro warning y ya no sabemos que hacer, nos puede ayudar por favor profesor?

**Comment by norman-ipn** [comment]
El operador & obtiene la dirección de una variable. si la variable es un caracter obtienen un apuntador a caracter, si la variable es un arreglo de apuntadores (char *variable[]), obtienes un triple apuntador.
La violación del segmento es porque no han reservado memoria o están entrando a una región no reservada.
